# Generated by Django 5.0.3 on 2024-03-22 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('idPersona', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('Nombres', models.CharField(max_length=60)),
                ('Apellidos', models.CharField(max_length=60)),
                ('Identificacion', models.CharField(max_length=10)),
                ('FechaNacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idRol', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('RolName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rol_Opciones',
            fields=[
                ('idOpcion', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('NombreOpcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rol_RolOpciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RolOpciones_idOpcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_prueba.rol_opciones')),
                ('Rol_idRol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_prueba.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idUsuario', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Mail', models.CharField(max_length=120)),
                ('SessionActive', models.CharField(max_length=1)),
                ('Persona_idPersona2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_prueba.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaIngreso', models.DateField()),
                ('FechaCierre', models.DateField()),
                ('Usuarios_idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_prueba.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Rol_Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rol_idRol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_prueba.rol')),
                ('Usuarios_idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_prueba.usuarios')),
            ],
        ),
    ]
